blueprints/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, session, jsonify
from exts import db
from models import UserModel, CurrentModel, TargetModel
from blueprints.forms import RegisterForm, LoginForm
from werkzeug.security import generate_password_hash, check_password_hash


bp = Blueprint("auth", __name__, url_prefix="/")

@bp.route('/login', methods=['GET','POST'])
def login ():
    if request.method == 'GET':
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = db.session.execute(db.select(UserModel).filter_by(email=email)).scalar()
            if not user:
                return render_template("notregistered.html")
            if check_password_hash(user.password, password):
                session['user_id']=user.id
                target = db.session.execute(db.select(TargetModel).filter_by(author_id=user.id)).scalar()
                if target.firsttime:
                    target.firsttime = 0
                    db.session.commit()
                    return redirect(url_for("progress.settarget"))
                else:
                    return redirect('/')
            else:
                return render_template("wronginfo.html")
        else:
            return render_template("wronginfo.html")




@bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template("register.html")
    else:
        form = RegisterForm(request.form)
        if form.validate():
            firstname = form.firstname.data
            lastname = form.lastname.data
            email = form.email.data
            password = form.password.data
            username = firstname[0].upper() + lastname[0].upper()
            user = UserModel(username=username, firstname=firstname, lastname=lastname, email=email, password=generate_password_hash(password))
            db.session.add(user)
            db.session.commit()
            user_id = user.id
            current = CurrentModel(author_id=user_id)
            target = TargetModel(author_id=user_id)
            db.session.add(target)
            db.session.add(current)
            db.session.commit()
            return render_template("registerok.html")
        else:
            if form.email.errors:
                return render_template("alreadyregistered.html")
            else:
                return redirect(url_for("auth.register"))

@bp.route('/logout')
def logout():
    session.clear()
    return redirect('/')

blueprints/progress.py
from flask import Blueprint, render_template, request, redirect, url_for, session, jsonify,g

from decorators import loginrequired
from exts import db
from models import TargetModel, UserModel, CurrentModel
from blueprints.forms import TargetForm, CurrentForm
from datetime import datetime


bp = Blueprint("progress", __name__, url_prefix="/")


@bp.route('/')
def index():
    if g.user:
        user_id = session['user_id']
        target = db.session.execute(db.select(TargetModel).filter_by(author_id=user_id)).scalar()
        current = db.session.execute(db.select(CurrentModel).filter_by(author_id=user_id)).scalar()

        currentdate = datetime.today().date()
        targetdate = target.targetdate
        startdate = target.startdate
        if targetdate is None or startdate is None or startdate>currentdate or currentdate>targetdate:
            progresstodate = 0
        else:
            dayspassed = (currentdate - startdate).days
            totaldays = (targetdate - startdate).days
            if totaldays>0:
                progresstodate = round((dayspassed/totaldays)*100)
            else:
                progresstodate = 0

        targetleetcode = target.targetleetcode
        currentleetcode = current.currentleetcode
        if targetleetcode is None or currentleetcode is None:
            leetcodeprogress = 0
        else:
            if currentleetcode>=targetleetcode:
                leetcodeprogress = 100
            else:
                leetcodeprogress = round((currentleetcode/targetleetcode)*100)

        targetproject = target.targetproject
        currentproject = current.currentproject
        if targetproject is None or currentproject is None:
            projectprogress = 0
        else:
            if currentproject>=targetproject:
                projectprogress = 100
            else:
                projectprogress = round((currentproject/targetproject)*100)

        resume = 1 if current.resume is True else 0
        bq = 1 if current.bq is True else 0
        tq = 1 if current.tq is True else 0
        mock = 1 if current.mock is True else 0
        interviewprogress = round((resume+bq+tq+mock)/4*100)

        currentprogress = round(leetcodeprogress*0.4+projectprogress*0.4+interviewprogress*0.2)

        if currentprogress >= progresstodate:
            barcolor = "#87ceeb"
        else:
            barcolor = "#8b0000"
    else:
        leetcodeprogress = 0
        projectprogress = 0
        interviewprogress = 0
        currentprogress = 0
        progresstodate = 0
        barcolor = "#4caf50"
    return render_template("index.html",
                           leetcodeprogress=leetcodeprogress,
                           projectprogress=projectprogress,
                           interviewprogress=interviewprogress,
                           currentprogress=currentprogress,
                           progresstodate=progresstodate,
                           barcolor=barcolor)


@bp.route('/leetcode', methods=['GET', 'POST'])
@loginrequired
def leetcode():
    user_id = session['user_id']
    current = db.session.execute(db.select(CurrentModel).filter_by(author_id=user_id)).scalar()
    target = db.session.execute(db.select(TargetModel).filter_by(author_id=user_id)).scalar()

    if request.method == "GET":
        currentdate = datetime.today().date()
        targetdate = target.targetdate
        startdate = target.startdate
        if targetdate is None or startdate is None or startdate > currentdate or currentdate > targetdate:
            progresstodate = 0
        else:
            dayspassed = (currentdate - startdate).days
            totaldays = (targetdate - startdate).days
            if totaldays > 0:
                progresstodate = round((dayspassed / totaldays) * 100)
            else:
                progresstodate = 0

        targetleetcode = target.targetleetcode
        currentleetcode = current.currentleetcode
        if targetleetcode is None or currentleetcode is None:
            leetcodeprogress = 0
        else:
            if currentleetcode >= targetleetcode:
                leetcodeprogress = 100
            else:
                leetcodeprogress = round((currentleetcode / targetleetcode) * 100)

        return render_template("leetcode.html",
                               currentleetcode=currentleetcode,
                               leetcodeprogress=leetcodeprogress,
                               progresstodate= progresstodate)
    else:
        form = CurrentForm(request.form)
        if form.validate():
            current.currentleetcode = form.currentleetcode.data
            db.session.commit()
        else:
            redirect(url_for("progress.leetcode"))
    return redirect(url_for("progress.leetcode"))



@bp.route('/project', methods=['GET', 'POST'])
@loginrequired
def project():
    user_id = session['user_id']
    current = db.session.execute(db.select(CurrentModel).filter_by(author_id=user_id)).scalar()
    target = db.session.execute(db.select(TargetModel).filter_by(author_id=user_id)).scalar()

    if request.method == "GET":
        currentdate = datetime.today().date()
        targetdate = target.targetdate
        startdate = target.startdate
        if targetdate is None or startdate is None or startdate > currentdate or currentdate > targetdate:
            progresstodate = 0
        else:
            dayspassed = (currentdate - startdate).days
            totaldays = (targetdate - startdate).days
            if totaldays > 0:
                progresstodate = round((dayspassed / totaldays) * 100)
            else:
                progresstodate = 0

        targetproject = target.targetproject
        currentproject = current.currentproject
        if targetproject is None or currentproject is None:
            projectprogress = 0
        else:
            if currentproject >= targetproject:
                projectprogress = 100
            else:
                projectprogress = round((currentproject / targetproject) * 100)

        return render_template("project.html",
                               currentproject=currentproject,
                              projectprogress=projectprogress,
                               progresstodate= progresstodate)
    else:
        form = CurrentForm(request.form)
        if form.validate():
            current.currentproject = form.currentproject.data
            db.session.commit()
        else:
            redirect(url_for("progress.project"))
    return redirect(url_for("progress.project"))


@bp.route('/interview', methods=['GET', 'POST'])
@loginrequired
def interview():
    user_id = session['user_id']
    current = db.session.execute(db.select(CurrentModel).filter_by(author_id=user_id)).scalar()
    target = db.session.execute(db.select(TargetModel).filter_by(author_id=user_id)).scalar()

    resume = 1 if current.resume is True else 0
    bq = 1 if current.bq is True else 0
    tq = 1 if current.tq is True else 0
    mock = 1 if current.mock is True else 0


    if request.method == "GET":
        currentdate = datetime.today().date()
        targetdate = target.targetdate
        startdate = target.startdate
        if targetdate is None or startdate is None or startdate > currentdate or currentdate > targetdate:
            progresstodate = 0
        else:
            dayspassed = (currentdate - startdate).days
            totaldays = (targetdate - startdate).days
            if totaldays > 0:
                progresstodate = round((dayspassed / totaldays) * 100)
            else:
                progresstodate = 0

        currentinterview = resume + bq + tq + mock
        interviewprogress = round(currentinterview/4*100)

        return render_template("interview.html",
                              interviewprogress=interviewprogress,
                               progresstodate= progresstodate,
                               resume = resume,
                               bq = bq,
                               tq = tq,
                               mock = mock)
    else:
        form = CurrentForm(request.form)
        if form.validate():
            current.resume = form.resume.data
            current.bq = form.bq.data
            current.tq = form.tq.data
            current.mock = form.mock.data
            db.session.commit()
        else:
            redirect(url_for("progress.interview"))
    return redirect(url_for("progress.interview"))


@bp.route('/settartget', methods=['GET', 'POST'])
@loginrequired
def settarget():
    user_id = session["user_id"]
    if request.method == 'GET':
        today = datetime.today().date()
        target = db.session.execute(db.select(TargetModel).filter_by(author_id=user_id).order_by(TargetModel.id.desc())).scalar()
        return render_template("settarget.html",target=target, today=today)
    else:
        form = TargetForm(request.form)
        if form.validate():
            targetleetcode = form.targetleetcode.data
            targetproject = form.targetproject.data
            targetdate = form.targetdate.data
            if form.startdate.data is None:
                startdate = datetime.today().date()
            else:
                startdate = form.startdate.data
            target = db.session.execute(db.select(TargetModel).filter_by(author_id=user_id)).scalar()
            if target is None:
                target = TargetModel(targetleetcode=targetleetcode, targetproject=targetproject,
                                     targetdate=targetdate, startdate=startdate, author=g.user)
                db.session.add(target)
            else:
                if targetleetcode:
                    target.targetleetcode = targetleetcode
                if targetproject:
                    target.targetproject = targetproject
                if targetdate:
                    target.targetdate = targetdate
                if startdate:
                    target.startdate = startdate

templates/alreadyregistered.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/register.css')}}">
{% endblock %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <div class="container">
        <h3 class="reg">Sorry, this email is already registered.</h3>
        <h3 class="reg">Please login.</h3>
        <ul>
            <li class="button">
                <button class="blue" onclick="window.location.href='{{url_for('auth.login')}}'">Login</button>
            </li>
        </ul>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{url_for('static', filename='css/base.css')}}">
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="header">
        <ul>
            <li class="header">
                <a class="header" href="{{url_for('progress.index')}}">Home</a>
            </li>
            <li class="header">
                <a class="header" href="{{url_for('progress.leetcode')}}">Leetcode</a>
            </li>
            <li class="header">
                <a class="header" href="{{url_for('progress.project')}}">Project</a>
            </li>
            <li class="header">
                <a class="header" href="{{url_for('progress.interview')}}">Interview</a>
            </li>
            {% if user %}
                <li class="user">
                    <a class="log" href="{{url_for('auth.logout')}}">Logout</a>
                </li>
                <li class="user">
                    <a class="log" href="{{url_for('progress.settarget')}}">{{user.username}}</a>
                </li>
            {% else %}
                <li class="user">
                    <a class="log" href="{{url_for('auth.register')}}">Register</a>
                </li>
                <li class="user">
                    <a class="log" href="{{url_for('auth.login')}}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
    <div>
        {% block body %}{% endblock %}
    </div>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/pages.css')}}">
{% endblock %}

{% block title %}
    Home
{% endblock %}

{% block body %}
    <div class="overview">
        <div class="overviewtitle">
            <h3>Overall Progress</h3>
        </div>
        <div class="question">
                <p class="overall">Your overall progress:<span class="percentage">{{currentprogress}}%</span></p>
                <p class="overall">Expected progress by now:<span class="percentage">{{progresstodate}}%</span></p>
        </div>
        <div class="answer">
            <div class="barcontainer">
                <div class="upper">
                    <div style="width: {{currentprogress}}%; background-color: {{barcolor}}; height: 25px; margin: 0;"></div>
                </div>
            </div>
            <div class="barcontainer">
                <div class="lower">
                    <div style="width: {{progresstodate}}%; background-color: #4caf50; height: 25px; margin: 0;"></div>
                </div>
            </div>
        </div>
        <div class="comment">Please go to each section to update your progress.</div>
    </div>
    <a class="section" href="{{url_for('progress.leetcode')}}">
        <div class="area" id="leetcode">
            <div class="suboverview">
                <table>
                    <tr>
                        <td class="left">
                            <div class="bullet">
                                Leetcode<br>Progress
                            </div>
                        </td>
                        <td class="middle">
                            <p class="suboverall">Your <b>Leetcode</b> progress:<span class="subpercentage">{{leetcodeprogress}}%</span></p>
                            <p class="suboverall">Expected progress by now:<span class="subpercentage">{{progresstodate}}%</span></p>
                        </td>
                        <td class="right">
                            <div class="subupper">
                                <div style="width: {{leetcodeprogress}}%; background-color: #87ceeb; height: 20px; margin: 0;"></div>
                            </div>
                            <div class="blank"></div>
                            <div class="sublower">
                                <div style="width: {{progresstodate}}%; background-color: #4caf50; height: 20px; margin: 0;"></div>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </a>
    <a class="section" href="{{url_for('progress.project')}}">
        <div class="area" id="project">
            <div class="suboverview">
                <table>
                    <tr>
                        <td class="left">
                            <div class="bullet">
                                Project<br>Progress
                            </div>
                        </td>
                        <td class="middle">
                            <p class="suboverall">Your <b>Project</b> progress:<span class="subpercentage">{{projectprogress}}%</span></p>
                            <p class="suboverall">Expected progress by now:<span class="subpercentage">{{progresstodate}}%</span></p>
                        </td>
                        <td class="right">
                            <div class="subupper">
                                <div style="width: {{projectprogress}}%; background-color: #87ceeb; height: 20px; margin: 0;"></div>
                            </div>
                            <div class="blank"></div>
                            <div class="sublower">
                                <div style="width: {{progresstodate}}%; background-color: #4caf50; height: 20px; margin: 0;"></div>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </a>
    <a class="section" href="{{url_for('progress.interview')}}">
        <div class="area" id="interview">
            <div class="suboverview">
                <table>
                    <tr>
                        <td class="left">
                            <div class="bullet">
                                Interview<br>Progress
                            </div>
                        </td>
                        <td class="middle">
                            <p class="suboverall">Your <b>Interview</b> progress:<span class="subpercentage">{{interviewprogress}}%</span></p>
                            <p class="suboverall">Expected progress by now:<span class="subpercentage">{{progresstodate}}%</span></p>
                        </td>
                        <td class="right">
                            <div class="subupper">
                                <div style="width: {{interviewprogress}}%; background-color: #87ceeb; height: 20px; margin: 0;"></div>
                            </div>
                            <div class="blank"></div>
                            <div class="sublower">
                                <div style="width: {{progresstodate}}%; background-color: #4caf50; height: 20px; margin: 0;"></div>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </a>
{% endblock %}

templates/interview.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/pages.css')}}">
{% endblock %}

{% block title %}
    Interview
{% endblock %}

{% block body %}
    <div class="area" id="interview">
        <div class="suboverview">
            <table>
                <tr>
                    <td class="left">
                        <div class="bullet">
                            Interview<br>Progress
                        </div>
                    </td>
                    <td class="middle">
                        <p class="suboverall">Your <b>Interview</b> progress:<span class="subpercentage">{{interviewprogress}}%</span></p>
                        <p class="suboverall">Expected progress by now:<span class="subpercentage">{{progresstodate}}%</span></p>
                    </td>
                    <td class="right">
                        <div class="subupper">
                            <div style="width: {{interviewprogress}}%; background-color: #87ceeb; height: 20px; margin: 0;"></div>
                        </div>
                        <div class="blank"></div>
                        <div class="sublower">
                            <div style="width: {{progresstodate}}%; background-color: #4caf50; height: 20px; margin: 0;"></div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <form id="interviewupdate" method="POST">
        <div class="currentupdate">
            <ul>
                <li class="checklist">
                    I have completed my resume.
                    {% if resume %}
                    <input type="checkbox" name="resume" value="True" checked>
                    {% else %}
                    <input type="checkbox" name="resume" value="True">
                    {% endif %}
                </li>
                <br/>
                <li class="checklist">
                    I am prepared for bq.
                    {% if bq %}
                    <input type="checkbox" name="bq" value="True" checked>
                    {% else %}
                    <input type="checkbox" name="bq" value="True">
                    {% endif %}
                </li>
                <br/>
                <li class="checklist">
                    I am prepared for tq.
                    {% if tq %}
                    <input type="checkbox" name="tq" value="True" checked>
                    {% else %}
                    <input type="checkbox" name="tq" value="True">
                    {% endif %}
                </li>
                <br/>
                <li class="checklist">
                    I have completed mock interview.
                    {% if mock %}
                    <input type="checkbox" name="mock" value="True" checked>
                    {% else %}
                    <input type="checkbox" name="mock" value="True">
                    {% endif %}
                </li>
                <li class="updatebutton">
                    <button type="submit">Update</button>
                </li>
            </ul>
        </div>
    </form>

{% endblock %}

templates/leetcode.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/pages.css')}}">
{% endblock %}

{% block title %}
    Leetcode
{% endblock %}

{% block body %}
    <div class="area" id="leetcode">
        <div class="suboverview">
            <table>
                <tr>
                    <td class="left">
                        <div class="bullet">
                            Leetcode<br>Progress
                        </div>
                    </td>
                    <td class="middle">
                        <p class="suboverall">Your <b>Leetcode</b> progress:<span class="subpercentage">{{leetcodeprogress}}%</span></p>
                        <p class="suboverall">Expected progress by now:<span class="subpercentage">{{progresstodate}}%</span></p>
                    </td>
                    <td class="right">
                        <div class="subupper">
                            <div style="width: {{leetcodeprogress}}%; background-color: #87ceeb; height: 20px; margin: 0;"></div>
                        </div>
                        <div class="blank"></div>
                        <div class="sublower">
                            <div style="width: {{progresstodate}}%; background-color: #4caf50; height: 20px; margin: 0;"></div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <form id="leetcodeupdate" method="POST">
        <div class="currentupdate">
            I have solved
            <input class="currentupdate" type="number" min="1" max="9999" name="currentleetcode" placeholder="{{currentleetcode}}">
             leetcode problems.
            <button type="submit">Update</button>
        </div>
    </form>

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/register.css')}}">
{% endblock %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <div class="container">
        <h3 class="reg">Please login</h3>
        <form id="login" action="" target="" method="POST">
            <ul>
                <li>
                    <input class="reg" type="email" name="email" placeholder="Email" required>
                </li>
                <li>
                    <input id="password" class="reg" type="password" name="password" placeholder="Password" required>
                </li>
                <li class="button">
                    <button class="blue" type="submit">Submit</button>
                    <button class="grey" type="reset">Reset</button>
                </li>
            </ul>
        </form>
    </div>
{% endblock %}

templates/notregistered.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/register.css')}}">
{% endblock %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <div class="container">
        <h3 class="reg">This email was not registered.</h3>
        <h3 class="reg">Please register.</h3>
        <ul>
            <li class="button">
                <button class="blue" onclick="window.location.href='{{url_for('auth.register')}}'">Register</button>
            </li>
        </ul>
    </div>
{% endblock %}

templates/project.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/pages.css')}}">
{% endblock %}

{% block title %}
    Project
{% endblock %}

{% block body %}
    <div class="area" id="project">
        <div class="suboverview">
            <table>
                <tr>
                    <td class="left">
                        <div class="bullet">
                            Project<br>Progress
                        </div>
                    </td>
                    <td class="middle">
                        <p class="suboverall">Your <b>Project</b> progress:<span class="subpercentage">{{projectprogress}}%</span></p>
                        <p class="suboverall">Expected progress by now:<span class="subpercentage">{{progresstodate}}%</span></p>
                    </td>
                    <td class="right">
                        <div class="subupper">
                            <div style="width: {{projectprogress}}%; background-color: #87ceeb; height: 20px; margin: 0;"></div>
                        </div>
                        <div class="blank"></div>
                        <div class="sublower">
                            <div style="width: {{progresstodate}}%; background-color: #4caf50; height: 20px; margin: 0;"></div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <form id="projectupdate" method="POST">
        <div class="currentupdate">
            I have completed
            <input class="currentupdate" type="number" min="1" max="9999" name="currentproject" placeholder="{{currentproject}}">
             projects.
            <br/>
            <button type="submit">Update</button>
        </div>
    </form>

{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/register.css')}}">
{% endblock %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <div class="container">
        <h3 class="reg">Create an Account</h3>
        <form id="register" action="" target="" method="POST">
            <ul>
                <li class="name">
                    <input class="regname" type="text" name="firstname" placeholder="First Name" required>
                    <input class="regname" type="text" name="lastname" placeholder="Last Name" required>
                </li>
                <li>
                    <input class="reg" type="email" name="email" placeholder="Email" required>
                </li>
                <li>
                    <input id="password" class="reg" type="password" placeholder="Password (no more than 20 letters)" required>
                </li>
                <li>
                    <input id="confirmpwd" class="reg" type="password" name="password" placeholder="Confirm Password" required>
                </li>

                <span id="error"></span>

                <li class="button">
                    <button class="blue" type="submit">Submit</button>
                    <button class="grey" type="reset">Reset</button>
                </li>
            </ul>
        </form>
    </div>
    <script>
        document.getElementById("register").addEventListener('submit', function(event){
            const pwd = document.getElementById("password").value;
            const cpwd = document.getElementById("confirmpwd").value;
            const message = document.getElementById("error");
            if (pwd !== cpwd) {
                message.textContent = "Please enter same password.";
                event.preventDefault();
            }
            else {
                message.textContent = "";
            }

        });
    </script>

{% endblock %}

templates/registerok.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/register.css')}}">
{% endblock %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <div class="container">
        <h3 class="reg">You have successfully registered!</h3>
        <h3 class="reg">Please login.</h3>
        <ul>
            <li class="button">
                <button class="blue" onclick="window.location.href='{{url_for('auth.login')}}'">Login</button>
            </li>
        </ul>
    </div>
{% endblock %}

templates/wronginfo.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/register.css')}}">
{% endblock %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <div class="container">
        <h3 class="reg">Incorrect password.</h3>
        <h3 class="reg">Please try again.</h3>
        <ul>
            <li class="button">
                <button class="blue" onclick="window.location.href='{{url_for('auth.login')}}'">Login</button>
            </li>
        </ul>
    </div>
{% endblock %}